sudo: false
language: node_js
node_js:
- iojs
- '0.12'
- '0.10'
notifications:
  slack:
    secure: QptyXYsvdAlKRB86ahzlc7BSZ5QpCrdWgRrMaXTeuAKMdDLSJv7sKhfNz+GDQN/zVHi966dFCdJ1kMMCPtQSIn+kg+t5aSmW4GWWJ+BDrEPnN6LlRwgUuzIiDgEqW/ZkXC6gvlz5eeIB5uUmvQinx6x2T7IiXkLUA7C3YUHhlFo=
